In [1]:
import numpy as np

In [4]:
a = [i for i in range (10)]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
b = np.array(a)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
c = np.array([0,1,2,3,4,5,6,7,8,9])
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
type(b)

numpy.ndarray

In [9]:
b = np.array(b, dtype = float)
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
b[0]

0.0

In [15]:
visota=b.ndim
visota

1

In [16]:
harakteristiki=b.shape
harakteristiki

(10,)

## 2D array

In [29]:
b=np.array([[i for i in range (10)],
            [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
            [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [30]:
b.shape

(3, 10)

In [31]:
b.size

30

In [32]:
b[1,1]

11

In [33]:
b[0:2,0:3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [35]:
c = b[1:,5:]
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [36]:
c[1, 4] = 999
c

array([[ 15,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [37]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

чтобы сделать матрицы независимыми друг от друга:

In [41]:
c = b[1:,5:].copy()
c

array([[ 15,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

## Data types

In [42]:
b = np.array([0,1,2,3,4,5,6,7,8,9], dtype=np.float32)
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [44]:
b = np.array([0,1,2,3,4,5,6,7,8,9], dtype=np.int64) #64bit - занимает больше места, чем 32
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])