# VECTORS

## create vectors

In [1]:
import numpy as np

In [2]:
a=np.array([0,1,2,3,4])

In [3]:
b=np.array([5,6,7,8,9])

In [4]:
a.size

5

In [5]:
b.size

5

In [6]:
a.shape

(5,)

In [7]:
b.shape

(5,)

## sum vectors

In [8]:
c=a+b
c

array([ 5,  7,  9, 11, 13])

another way to sum:

In [9]:
c=np.add(a,b)
c

array([ 5,  7,  9, 11, 13])

## subtraction vectors

In [10]:
a=np.array([5,4,8,4,3])
b=np.array([3,5,7,1,3])

In [11]:
c=a-b
c

array([ 2, -1,  1,  3,  0])

another way to substract:

In [12]:
d=np.subtract(a,b)
d

array([ 2, -1,  1,  3,  0])

## multiplication vectors

In [13]:
a=np.array([5,4,8,4,3])
a

array([5, 4, 8, 4, 3])

In [14]:
c=a*2
c

array([10,  8, 16,  8,  6])

In [15]:
c=-10*a
c

array([-50, -40, -80, -40, -30])

In [16]:
c=0.5*a
c

array([2.5, 2. , 4. , 2. , 1.5])

another way to multiplication

In [17]:
a.dot(-10)

array([-50, -40, -80, -40, -30])

In [18]:
np.dot(-10,a)

array([-50, -40, -80, -40, -30])

In [19]:
np.multiply(-10,a)

array([-50, -40, -80, -40, -30])

## scalar multiplication vectors

In [20]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [21]:
sp=a[0]*b[0]+a[1]*b[1]+a[2]*b[2]
sp

32

another way to multiplication vectors

In [22]:
a @ b

32

In [23]:
sp=np.dot(a,b)
sp

32

# MATRIX

## create matrix

In [24]:
A=np.array([[0,1],
            [2,3],
            [4,5]])
A.shape

(3, 2)

In [25]:
B=np.array([[6,7],
            [8,9],
            [10,11]])
B.shape

(3, 2)

## sum,subtract,multiply scalar matrix

In [26]:
C = A+B
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

another way to sum matrix

In [27]:
C=np.add(A,B)
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [28]:
A=np.array([[11,13],
            [16,9],
            [8,15]])
B=np.array([[6,7],
            [8,9],
            [10,11]])
D=A-B
D

array([[ 5,  6],
       [ 8,  0],
       [-2,  4]])

In [29]:
D=np.subtract(A,B)
D

array([[ 5,  6],
       [ 8,  0],
       [-2,  4]])

In [30]:
X=np.array([[1,2],[3,4]])
X

array([[1, 2],
       [3, 4]])

In [31]:
Y=X*3
Y

array([[ 3,  6],
       [ 9, 12]])

In [32]:
Y=np.dot(X,3)
Y

array([[ 3,  6],
       [ 9, 12]])

## multiply matrix

In [33]:
X1=np.array([[1,2],
             [3,4],
             [5,6]])
X1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
X2=np.array([[7,8,9,10],
             [11,12,13,14]])
X2

array([[ 7,  8,  9, 10],
       [11, 12, 13, 14]])

число столбцов первой матрицы = числу строк второй матрицы

In [35]:
X1.shape[1]==X2.shape[0]

True

In [36]:
X1.shape, X2.shape

((3, 2), (2, 4))

In [37]:
Z=np.dot(X1,X2)
Z

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

In [38]:
Z.shape

(3, 4)

как получена Z

In [39]:
Z[0,0]

29

In [40]:
X1[0,0]*X2[0,0]+X1[0,1]*X2[1,0]

29

In [41]:
Z[0,1]

32

In [42]:
X1[0,0]*X2[0,1]+X1[0,1]*X2[1,1]

32

## матрицы в квадрат

In [43]:
A=np.array([[0,1,2],
            [3,4,5],
            [6,7,8]])

In [44]:
A_square=np.dot(A,A)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
A_square=np.linalg.matrix_power(A,2)
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

## единичная матрица
квадратная матрица с единицами по главной диагонали и нулями в остальных ячейках

In [46]:
I=np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

при умножение матрицы на единичную, всегда получаем исходную

In [47]:
np.dot(A,I)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

## транспонирование

In [48]:
X=np.array([[1,2],
            [3,4],
            [5,6]])

In [49]:
Xt=X.transpose()
Xt

array([[1, 3, 5],
       [2, 4, 6]])

In [50]:
Xt=X.T
Xt

array([[1, 3, 5],
       [2, 4, 6]])

пример применения:

In [51]:
X=np.array([[1,2],
            [3,4],
            [5,6]])

In [52]:
Y=np.array([[1,2],
            [3,4],
            [5,6],
            [7,8]])

In [53]:
Yt=Y.T
Yt

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [54]:
np.dot(X,Yt)

array([[ 5, 11, 17, 23],
       [11, 25, 39, 53],
       [17, 39, 61, 83]])

## вычисление определителя и ранга
Определитель матрицы - это число, которое в каком-то смысле "определяет" её свойства. Например, обратную матрицу можно посчитать только для матрицы,определитель которой не равен (по аналогии с тем, что делить можно только на числа, не равные).
Ранг матрицы - это число линейно независимых строк данной матрицы.

In [55]:
A=np.array([[0,1,2],
            [3,4,5],
            [6,7,8]])

In [56]:
np.linalg.det(A) #только для квадратных

0.0

In [57]:
np.linalg.matrix_rank(A)

2

In [58]:
B=np.array([[7,4,5],
            [8,3,2],
            [6,10,12]])

In [59]:
np.linalg.det(B)

85.99999999999989

In [60]:
np.linalg.matrix_rank(B)

3

## обратная матрица
Это матрица, которая при умножении на исходную матрицу даёт единичную матрицу

In [61]:
B

array([[ 7,  4,  5],
       [ 8,  3,  2],
       [ 6, 10, 12]])

In [62]:
B_inv=np.linalg.inv(B)
B_inv

array([[ 0.18604651,  0.02325581, -0.08139535],
       [-0.97674419,  0.62790698,  0.30232558],
       [ 0.72093023, -0.53488372, -0.12790698]])

In [63]:
B_inv_inv=np.linalg.inv(B_inv)
B_inv_inv

array([[ 7.,  4.,  5.],
       [ 8.,  3.,  2.],
       [ 6., 10., 12.]])

## автоматическое создание массивов

только нули:

In [65]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

только единицы:

In [80]:
a = np.ones((5,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

векторы. по дэфолту с нуля:

In [81]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.arange(14,18)

array([14, 15, 16, 17])

с шагом:

In [74]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [75]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [77]:
np.arange(0,4,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [78]:
np.linspace(0,9.9,100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

степени числа 10:

In [79]:
np.logspace(0,3,4)

array([   1.,   10.,  100., 1000.])

## генерация случайных чисел

In [82]:
np.random.sample()

0.4175406759411554

In [83]:
np.random.sample(3)

array([0.64842593, 0.02469678, 0.03336947])

In [84]:
np.random.sample((2,3))

array([[0.06676515, 0.87418919, 0.84430326],
       [0.9010795 , 0.62837275, 0.15849639]])

In [86]:
np.random.sample((5,5,3))

array([[[0.92931824, 0.25905311, 0.9724703 ],
        [0.01112163, 0.44064114, 0.11651771],
        [0.30718898, 0.67006172, 0.71876267],
        [0.37497391, 0.23078558, 0.4417345 ],
        [0.83572993, 0.67339316, 0.63986341]],

       [[0.94091235, 0.50250447, 0.01907906],
        [0.82301862, 0.35369631, 0.17367484],
        [0.83559465, 0.86424492, 0.68406276],
        [0.07240854, 0.15136706, 0.27867884],
        [0.94257573, 0.90348974, 0.96976894]],

       [[0.24309799, 0.89818797, 0.04030188],
        [0.56867343, 0.82555158, 0.71977831],
        [0.27081013, 0.25493822, 0.70088432],
        [0.79692244, 0.50224796, 0.53571648],
        [0.51075918, 0.8534039 , 0.43980446]],

       [[0.4990402 , 0.48482498, 0.67141636],
        [0.56369001, 0.143623  , 0.71346927],
        [0.79572353, 0.92344071, 0.26101374],
        [0.45202726, 0.24545935, 0.11028696],
        [0.96375504, 0.71727152, 0.26922381]],

       [[0.02634215, 0.67196574, 0.74113238],
        [0.16637662, 0.080

Функция  randn  из модуля  numpy.random  возвращает аналогичный массив, но уже взятый из нормального
распределения (со средним   и среднеквадратическим отклонением  ):

In [87]:
np.random.randn(3, 4)

array([[ 0.95516266, -0.17279964, -1.2553042 ,  0.50979966],
       [ 0.36789474,  0.37701126, -0.68751318, -1.40605508],
       [ 1.50515593,  1.85988929, -0.45316276, -0.01855959]])

Функция  randint  возвращает массив из целых чисел в указанном диапазоне:

In [88]:
np.random.randint(0, 100, (3, 4))

array([[86, 18, 87, 62],
       [ 6, 75, 15, 35],
       [70, 51, 37,  3]])

случайные числа из массива:

In [91]:
a=np.array([0,1,2,3,4,5,6,7,8,9])

In [92]:
np.random.choice(a)

7

## изменение формы массива

In [96]:
b=np.arange(12)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [97]:
b.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

если не знаешь сколько нужно столбцов:

In [98]:
np.reshape(b, (3,-1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

если не знаешь сколько нужно строк:

In [99]:
np.reshape(b,(-1,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

inplace:

In [101]:
b.resize(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

обратно в одномерный массив:

In [104]:
b=b.flatten()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

объединение массивов по вертикали:

In [111]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [112]:
b=np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [113]:
v=np.vstack((a,b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [109]:
np.concatenate((a,b),axis=0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

по горизонтали:

In [114]:
h=np.hstack((a,b))
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [115]:
np.concatenate((a,b),axis=1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

в глубину:

In [116]:
d=np.dstack((a,b))
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

## выбор данных

In [117]:
a = np.random.randint(0, 20, 10)
a

array([ 7,  5,  6, 11, 11, 17, 18,  6,  5,  1])

In [118]:
b = a[a > 10]
b

array([11, 11, 17, 18])

In [120]:
c = a[(a > 0) & (a % 2 ==0)] #and
c

array([ 6, 18,  6])

In [121]:
a[(a > 0) | (a % 3 ==0)] #or

array([ 7,  5,  6, 11, 11, 17, 18,  6,  5,  1])

In [122]:
np.where(a>10) #index

(array([3, 4, 5, 6]),)

In [123]:
a=[1,5,10]
b=[2,6,11]
np.where([True,False,True],a,b) #True from a, False from B

array([ 1,  6, 10])

## сортировка

In [139]:
a=np.array([[2, 4, 3, 3], 
            [2, 2, 2, 4], 
            [5, 2, 0, 3]])

Допустим, мы хотим отсортировать строки этого массива по второму столбцу. Мы можем сделать это вручную, задав индексы строк в нужном нам порядке:

In [140]:
a[[1,2,0],:]

array([[2, 2, 2, 4],
       [5, 2, 0, 3],
       [2, 4, 3, 3]])

Этот процесс можно автоматизировать с помощью метода  a.argsort . Данный метод возвращает массив из
индексов массива  a  в порядке их возрастания по заданной оси:

In [141]:
a.argsort(axis=0) #строки

array([[0, 1, 2, 0],
       [1, 2, 1, 2],
       [2, 0, 0, 1]])

В каждом столбце этого массива стоят индексы строк массива  a , расположенные в том порядке, в котором они бы
отсортировали данный столбец по возрастанию. Автоматизируем процесс сортировки массива  a  по второму
столбцу. Для этого нужно получить второй столбец из массива, полученного с помощью метода  a.argsort :

In [143]:
ind1 = a[:, 1].argsort()
 
ind1

array([1, 2, 0])

In [144]:
c = a[a[:, 1].argsort(), :]
 
c

array([[2, 2, 2, 4],
       [5, 2, 0, 3],
       [2, 4, 3, 3]])

## перемешивание

In [146]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
#inplace
np.random.shuffle(a)
a

array([2, 3, 4, 1, 0, 7, 5, 9, 6, 8])

двумерные массивы:

In [149]:
a=np.array([[2, 4, 3, 3], 
            [2, 2, 2, 4], 
            [5, 2, 0, 3]])
np.random.shuffle(a)
a

array([[5, 2, 0, 3],
       [2, 4, 3, 3],
       [2, 2, 2, 4]])

## математические действия с массивами

In [151]:
a = np.arange(0, 6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [152]:
b = np.arange(6, 12).reshape(2, 3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [153]:
a + b

array([[ 6,  8, 10],
       [12, 14, 16]])

In [154]:
a + 1

array([[1, 2, 3],
       [4, 5, 6]])

С помощью метода  a.sum  можно посчитать сумму всех значений массива. Если указать в этом методе ось  axis ,
сумма будет посчитана только вдоль этой оси:

In [155]:
print("Сумма всех элементов: {}".format(a.sum()))
print('Сумма по столбцам ("вдоль" строк): {}'.format(a.sum(axis=0)))
print('Сумма по строкам ("вдоль" столбцов): {}'.format(a.sum(axis=1)))

Сумма всех элементов: 15
Сумма по столбцам ("вдоль" строк): [3 5 7]
Сумма по строкам ("вдоль" столбцов): [ 3 12]


## broadcasting

https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

В определённых случаях мы можем выполнять операции сложения и умножения над матрицами разных размеров.
Концепция broadcasting заключается в том, что в некоторых случаях интерпретатор "догадывается", что одну массив
надо в каком-то измерении "растянуть" до соответствия со вторым массивом. 

In [156]:
a = np.array([[2, 5],
              [3, 4],
              [6, 1]])
b = np.array([1, 2])

Если мы попытаемся их сложить, интерпретатор заметит, что у них совпадает одно из измерений: у них обоих 
столбца. Поэтому интерпретатор как бы "растянет" массив  b  до размера 2*3 и прибавит его к массиву  a 

In [157]:
a+b

array([[3, 7],
       [4, 6],
       [7, 3]])

## Статистические функции
Вот несколько методов, позволяющих вычислить различные статистики массива  a :

a.min  - минимальное значение

a.max  - максимальное значение

a.mean  - среднее значение

a.std  - среднее квадратическое отклонение

Все эти значения считаются по всему массиву, либо вдоль определённой оси, если задан параметр  axis .

In [158]:
print("Минимальное значение: {}".format(a.min()))
 
print("Средние значения строк: {}".format(a.mean(axis=1)))
 
print("Средние квадратические отклонения столбцов: {}".format(a.mean(axis=0)))

Минимальное значение: 1
Средние значения строк: [3.5 3.5 3.5]
Средние квадратические отклонения столбцов: [3.66666667 3.33333333]


## Запись и чтение массивов из файла

In [159]:
np.save("a.npy", a)

In [160]:
a = np.load("a.npy")